services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ollama:
  #   image: ollama/ollama:latest
  #   restart: always
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ./volumes/ollama:/root/.ollama
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   entrypoint: ["/bin/sh", "-c", "ollama pull gemma3:4b && ollama serve"]

  mekeeli-api:
    image: mekeeli/mekeeli-api:${MEKEELI_API_VERSION:-latest}
    restart: always
    depends_on:
      - db
      - ollama
    env_file: mekeeli-api/.env
    environment:
      - ENVIRONMENT=production
      - OLLAMA_URL=http://ollama:11434
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/mekeeli_data:/app/data
      - ./volumes/uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  mekeeli-ui:
    image: mekeeli/mekeeli-ui:${MEKEELI_UI_VERSION:-latest}
    restart: always
 #   depends_on:
#      - mekeeli-api
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://mekeeli-api:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
